name: Hello World

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Starting..."

  pythonsetup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: echo "installing python...."

  runner:
    runs-on: ubuntu-latest
    needs: pythonsetup
    container:
      image: alpine:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Make script executable
        run: chmod +x runner/script.sh || true
      - name: Run script
        shell: bash
        run: sh ./runner/script.sh

  packageandpush:
    runs-on: ubuntu-latest
    needs: runner
    container:
      image: sergiopr89/deployer:latest
    steps:
      - uses: actions/checkout@v4
      - name: package
        id: package
        shell: bash
        run: |
          echo "packaging..."

  deploy:
    runs-on: ubuntu-latest
    needs: packageandpush
    container:
      image: sergiopr89/deployer:latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        id: deploy
        shell: bash
        run: |
          echo "deploying..."
