name: Hello World

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    container:
      image: alpine:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building Python project ðŸ”¥"

  test:
    runs-on: [self-hosted]
    needs: build
    container:
      image: python:3.12
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: test
        id: test
        shell: bash
        run: |
          #cd app/dummy_api/
          #pip install --upgrade pip
          #pip install -r ./requirements.txt
          #./test.sh
          echo "running tests..."

  packageandpush:
    runs-on: [self-hosted]
    needs: test
    container:
      image: sergiopr89/deployer:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: package
        id: package
        shell: bash
        run: |
          #cd app/
          #docker image build -t dummy_api .
          echo "packaging..."

  deploy:
    runs-on: [self-hosted]
    needs: packageandpush
    container:
      image: sergiopr89/deployer:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        id: deploy
        shell: bash
        run: |
          cd helm/
          helm upgrade --install dummy ./charts/basic-app \
            -f ./vars.yaml \
            --namespace dummy \
            --create-namespace \
            --atomic \
            --timeout 300s