name: Hello World

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Starting..."

  pythonsetup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: echo "instalando python..."

  runner:
    runs-on: ubuntu-latest
    needs: pythonsetup
    steps:
      - uses: actions/checkout@v4
      - name: Make script executable (safe)
        run: chmod +x runner/script.sh || true
      - name: Run script
        shell: bash
        run: ./runner/script.sh

  packageandpush:
    runs-on: ubuntu-latest
    needs: runner
    steps:
      - uses: actions/checkout@v4
      - name: package
        id: package
        shell: bash
        run: |
          #cd app/
          #docker image build -t dummy_api .
          echo "packaging..."

  deploy:
    runs-on: ubuntu-latest
    needs: packageandpush
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        id: deploy
        shell: bash
        run: |
          echo