name: Hello World

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building Python project ðŸ”¥"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: test
        id: test
        shell: bash
        run: |
          #cd app/dummy_api/
          #pip install --upgrade pip
          #pip install -r ./requirements.txt
          #./test.sh
          echo "running tests..."

  packageandpush:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: package
        id: package
        shell: bash
        run: |
          #cd app/
          #docker image build -t dummy_api .
          echo "packaging..."

  deploy:
    runs-on: ubuntu-latest
    needs: packageandpush
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        id: deploy
        shell: bash
        run: |
          # Simulamos el deploy para evitar fallos si no hay KUBECONFIG
          echo "Simulando deploy: helm upgrade --install dummy ./charts/basic-app -f ./vars.yaml --namespace dummy ..."